### ISSUE TITLE
ca apm nginx fieldpacks software  download

### ISSUE THREAD

**Issue by prashantnitt07** [CA-APM/ca-apm-fieldpack-activemq-broker#1]
Hi , 
I want to download C APM Ngins fieldpacks software . please send me URL or any link.

**Comment by ggrossbe** [comment]
Hi Prashant,

please see https://github.com/CA-APM/ca-apm-fieldpack-nginx. You can cloen or just download the zip from https://github.com/CA-APM/ca-apm-fieldpack-nginx/releases.

Ciao,
Guenter Grossberger

**Comment by htdavis** [comment]
Closing issue since it's not related to this repo.
